version: "3.8"
services:
  servidor:
    build:
      context: ${CONTEXTO}
      dockerfile: ./dockerfiles/ubuntu/Dockerfile
      args:
        - CONTEXTO=${CONTEXTO}
        - TZ=${TZ}
        - PROYECTO=${PROYECTO}
        - AUTOR=${AUTOR}
    image: ${AUTOR}/nginx
    container_name: nginx1
    hostname: ${HOSTNAME}
    env_file:
      - ./.env
    environment:
      - USUARIO=${USUARIO}
      - PASSWORD=${PASSWD}
    ports:
      - "${PORT_ORIGEN}:80"
    volumes:
      - ./logs:/root/logs